Sharness: Merge test scripts' stderr into stdout
Merge the test scripts' stderr into stdout to aid in debugging.

Test script errors written to stderr are kept separate from TAP output
on stdout.  This complicates test script debugging since diagnostics
from the scripts are not displayed in the correct order relative
to test result output.

However, this change now causes "tests/1000-chaos-rpm.t" to fail
during test #5 (build rpm) on some RH-based systems when processed
by automake's "tap-driver.sh":

> ERROR: 1000-chaos-rpm.t - too many tests run (expected 19, got 20)

But the test script runs without error when invoked directly so that
its output is not processed by "tap-driver.sh":

> # passed all 19 test(s)
> 1..19

Reference:
- https://www.gnu.org/savannah-checkouts/gnu/automake/manual/html_node/Use-TAP-with-the-Automake-test-harness.html

Tested:
- AlmaLinux 9.5, 8.10
- Arch Linux
- CentOS Linux Stream 9, 8.5.2111, 7.9.2009, 6.10
- Debian sid, 12.10, 11.11, 10.13, 9.13, 8.11, 7.11, 6.0.10, 5.0.10, 4.0
- Fedora 42, 41, 40
- FreeBSD 14.2, 13.5
- NetBSD 10.1, 9.4
- OpenBSD 7.6, 7.5
- openSUSE 15.6, 15.5
- Ubuntu 25.04, 24.04.2, 22.04.5, 20.04.6, 18.04.6, 16.04.7, 14.04.6

Succeeded (1000-chaos-rpm.t):
- AlmaLinux 8.10
- CentOS Linux 8.5.2111
- Fedora 42

Failed (1000-chaos-rpm.t):
- AlmaLinux 9.5
- CentOS Linux Stream 9
- Fedora 41, 40