Fix Libgcrypt warning gcry_thread_cbs is deprecated
In Libgcrypt 1.6, the GCRYCTL_SET_THREAD_CBS command for gcry_control()
was deprecated.  From /usr/include/gcrypt.h:

> NOTE: Since Libgcrypt 1.6 the thread callbacks are not anymore used.
> However we keep it to allow for some source code compatibility if used
> in the standard way.

When compiling with clang, this results in the following warning
(or error if CFLAGS=-Werror):

> munged/crypto.c:52:1: error: 'gcry_thread_cbs' is deprecated
>       [-Werror,-Wdeprecated-declarations]
> GCRY_THREAD_OPTION_PTHREAD_IMPL;
> ^
> /usr/include/gcrypt.h:225:17: note: expanded from macro
>       'GCRY_THREAD_OPTION_PTHREAD_IMPL'
>   static struct gcry_thread_cbs gcry_threads_pthread = {                \
>                 ^
> /usr/include/gcrypt.h:211:8: note: 'gcry_thread_cbs' has been explicitly
>       marked deprecated here
> struct gcry_thread_cbs
>        ^

A comment noting this change was added in commit 0812f9d.  This commit
conditionally compiles the affected code for Libgcrypt versions prior
to 1.6.

Tested on:
- Debian 7.11 (Libgcrypt 1.5.0)
- Debian 8.8 (Libgcrypt 1.6.3)
- Debian 9.0 (Libgcrypt 1.7.6-beta)

Signed-off-by: Chris Dunlap <cdunlap@llnl.gov>