Fix warning of default arg promotion to va_start
clang 3.9.0 generated the following warning:

> ctx.c:176:22: error: passing an object that undergoes default argument
>       promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]
>     va_start (vargs, opt);
>                      ^
> ctx.c:158:45: note: parameter of type 'munge_opt_t' (aka 'enum munge_opt')
>       is declared here
> mmunge_ctx_get (munge_ctx_t ctx, munge_opt_t opt, ...)
>                                             ^
> ctx.c:247:22: error: passing an object that undergoes default argument
>       promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]
>     va_start (vargs, opt);
>                      ^
> ctx.c:232:45: note: parameter of type 'munge_opt_t' (aka 'enum munge_opt')
>       is declared here
> munge_ctx_set (munge_ctx_t ctx, munge_opt_t opt, ...)
>                                             ^

In a variadic function, the type of the last required argument must be
self-promoting (i.e., the default promotions must not change its type).

This commit changes the type of the "opt" parameter in munge_ctx_get()
and munge_ctx_set() from munge_opt_t (aka "enum munge_opt") to int.

Reference:
- https://www.gnu.org/software/libc/manual/html_node/Variadic-Prototypes.html

Signed-off-by: Chris Dunlap <cdunlap@llnl.gov>