Spec: Remove libmunge.la on Fedora 36+
On Fedora 36, rpmbuild fails with:

> error: File not found: /tmp/rpm/BUILDROOT/munge-0.5.14.20220614.8438a3e-1.fc36.x86_64/usr/lib64/libmunge.la

The "libmunge.la" file is installed in the buildroot:

> libtool: install: /usr/bin/install -p .libs/libmunge.lai /tmp/rpm/BUILDROOT/munge-0.5.14.20220614.8438a3e-1.fc36.x86_64/usr/lib64/libmunge.la

However, Fedora 36 removes "*.la" files from buildroot.  As discussed
in commit 48fdfa5, Fedora Packaging Guidelines state that libtool
archives should not be included.  But "libmunge.la" is being retained
for now since its removal should be treated as an API/ABI change.
It will be removed on the next ABI change.

Fix the rpmbuild failure by conditionally excluding "libmunge.la"
from the devel %files on Fedora 36 or later.  Note that rpmbuild
succeeds on prior Fedora releases without this change.

Reference:
- https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/AMKKEGJZBMPE4IQHKGR65RXKF2NALSOP/
- https://fedoraproject.org/wiki/Changes/RemoveLaFiles
- https://docs.fedoraproject.org/en-US/packaging-guidelines/#packaging-static-libraries

Tested:
- AlmaLinux 9.0, 8.6
- CentOS Linux Stream 9, Stream 8, 8.5.2111, 7.9.2009
- Fedora 36, 35, 34, 33