Add support for OpenSSL 3.0
OpenSSL 3.0 changes the API and data types for calculating MACs, and
moves the implementations of "weak" cryptographic algorithms into a
legacy provider that is not loaded by default.

Update autoconf checks for the new API.  Add support for the new
EVP_MAC types and functions.  Note that EVP_MAC_final() and EVP_Q_mac()
have their passed-by-reference output length parameter typed as a
size_t ptr, whereas HMAC_Final() and HMAC() use an unsigned int ptr.
On LP64, this changes the expected size of the referenced variable from
32b to 64b; consequently, a temporary assignment to a size_t variable
must now be performed to convert from/to the underlying 32b int
referenced by the "dstlenp" parameter in mac_final() and mac_block().

Add support for specifying the underlying message digest algorithms
used in calculating MACs via the new OSSL_PARAM type since EVP_MD
ptrs can no longer be used for such, and add _mac_map_enum() to handle
this conversion.

Load the new legacy provider for implementations of Blowfish
(cipher 2), CAST5 (cipher 3), and RIPEMD160 (mac 4).  Also,
explicitly load the default provider which will not be loaded by
default since another provider (i.e., the legacy provider) is being
loaded.  Failure to load the default provider is considered a fatal
error; however, failure to load the legacy provider only generates a
warning message since none of those algorithms are used by default.
A failure to load the legacy provider has been explicitly tested to
ensure that attempts to encode or decode with those algorithms will
gracefully fail if needed without crashing munged.

Portability across OpenSSL versions is an increasing maze of twisty
little #if blocks, all different.

References:
- https://wiki.openssl.org/index.php/OpenSSL_3.0#Low_Level_APIs
- https://www.openssl.org/docs/man3.0/man7/migration_guide.html
- https://lwn.net/Articles/868536/
- crypto(7)
- EVP_MAC(3)
- EVP_MAC-HMAC(7)
- EVP_MD-MD5(7)
- EVP_MD-RIPEMD160(7)
- EVP_MD-SHA1(7)
- EVP_MD-SHA2(7)
- OSSL_PARAM(3)
- OSSL_PARAM_INT(3)
- OSSL_PROVIDER(3)
- OSSL_PROVIDER-default(7)
- OSSL_PROVIDER-legacy(7)

Tested:
- AlmaLinux 8.6
- Arch Linux
- CentOS Linux Stream 8, 8.5.2111, 7.9.2009, 6.10
- Debian GNU/kFreeBSD bookworm/sid [amd64, i386]
- Debian GNU/Linux 11.3, 10.12, 9.13, 8.11, 7.11, 6.0.10, 5.0.10, 4.0
- Fedora 35, 34, 33, 32, 31, 30, 29, 28
- FreeBSD 13.1, 13.0, 12.3, 12.2, 11.4
- NetBSD 9.2, 9.1, 9.0, 8.1
- OpenBSD 7.1, 7.0, 6.9
- openSUSE 15.4, 15.3, 15.2
- Raspbian GNU/Linux 10.12 [armv7l]
- Ubuntu 21.10, 20.04.4, 18.04.6, 16.04.7, 14.04.6, 12.04.5

Failed:
- AlmaLinux 9.0
    OpenSSL 3.0.1 14 Dec 2021
    0021-munged-valgrind.t 6 - check valgrind log for errors in munged
    0025-mungekey-valgrind.t 2 - check valgrind log for errors in mungekey
- CentOS Linux Stream 9
    OpenSSL 3.0.1 14 Dec 2021
    0025-mungekey-valgrind.t 2 - check valgrind log for errors in mungekey
- Debian GNU/Linux sid
    OpenSSL 3.0.3 3 May 2022
    0021-munged-valgrind.t 6 - check valgrind log for errors in munged
    0025-mungekey-valgrind.t 2 - check valgrind log for errors in mungekey
- Fedora 36
    OpenSSL 3.0.2 15 Mar 2022
    0021-munged-valgrind.t 6 - check valgrind log for errors in munged
    0025-mungekey-valgrind.t 2 - check valgrind log for errors in mungekey
- openSUSE 15.1
    OpenSSL 1.1.0i-fips 14 Aug 2018
    src/common/mac.c: In function '_mac_init':
    src/common/mac.c:306:12: error: assignment from incompatible
      pointer type [-Werror=incompatible-pointer-types]
        x->ctx = HMAC_CTX_new ();
- Ubuntu 22.04
    OpenSSL 3.0.2 15 Mar 2022
    0021-munged-valgrind.t 6 - check valgrind log for errors in munged
    0025-mungekey-valgrind.t 2 - check valgrind log for errors in mungekey