munged: Add clock_get_timespec using clock_gettime
Move conf.c:_timer_get_timespec() and conf.c:_timer_is_timespec_ge()
to the new file "clock.c" in order for timespec-related functions to
be shared outside of "conf.c".

_timer_get_timespec() is renamed to clock_get_timespec(), it
now specifies an int return value instead of void, and its use of
gettimeofday() is replaced with clock_gettime() since the former is
marked obsolescent and may be removed in a future version of POSIX.

_timer_is_timespec_ge() is renamed to clock_is_timespec_ge(), and
its function prototype now uses const struct timespec pointers.

Reference:
- https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html

Tested:
- AlmaLinux 8.4
- Arch Linux
- CentOS Stream 8, 8.4.2105, 7.9.2009
- Debian bookworm/sid, 11.0, 10.10, 9.13, 8.11
- Debian GNU/kFreeBSD bookworm/sid [amd64, i386]
- Fedora 34, 33, 32
- FreeBSD 13.0, 12.2, 11.4
- NetBSD 9.2, 9.1, 9.0, 8.1
- OpenBSD 6.9, 6.8, 6.7
- openSUSE 15.3, 15.2, 15.1
- Raspbian 10.10 [armv7l]
- Ubuntu 21.04, 20.04.3, 18.04.6, 16.04.7, 14.04.6

Failed:
- CentOS 6.10
- Debian 7.11, 6.0.10, 5.0.10, 4.0
- Ubuntu 12.04.5
  munged-clock.o: In function `clock_get_timespec':
  src/munged/clock.c:50: undefined reference to `clock_gettime'