Spec: Update "Requires" dependencies
Add a logrotate "Requires" dependency since a logrotate config is
included in the package.

Change the pkgconfig "BuildRequires" dependency to "Requires" since
pkgconfig is not needed to build the package.

Both of these should arguably be "Recommends" dependencies since the
package will still function correctly without them but in "diminished
capacity".  However, doing so causes rpmbuild to immediately fail on
CentOS 7.9.2009 with:

> error: line 33: Unknown tag: Recommends: logrotate

Using "Requires" instead allows rpmbuild to succeed.  The resulting
RPM installs successfully.  The service even starts successfully, but
a subsequent check of its status shows it immediately exits since the
"/run/munge" directory does not exist.  Note that this failure is
unrelated to the changed dependencies.

Reference:
- https://docs.fedoraproject.org/en-US/packaging-guidelines/#_dependency_types

Tested:
- AlmaLinux 9.0, 8.6
- CentOS Linux Stream 9, Stream 8, 8.5.2111
- Fedora 35, 34, 33

Failed:
- CentOS 7.9.2009

RPMs built via "rpmbuild -ta --with check munge-0.5.14.20220614.8438a3e.tar.xz".